import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";

const inter = Inter({
  style: "normal",
  weight: ["300", "400", "700"],
  display: "auto",
  subsets: ["latin"],
  variable: "--font-inter",
});

const apple = localFont({
  src: [
    {
      path: "../../public/font/AppleGaramond-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/font/AppleGaramond.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/AppleGaramond-Light.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-apple",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${apple.variable} ${inter.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
